#!/bin/bash

# Don't forget the trailing / on the source directory - if you omit it,
# it will copy the directory over, rather than just its contents.
# NOTE: no trailing slash on destination directory
export QA_SOURCE_DIR=/var/www/web-panel/public/
export QA_DEST_DIR=/var/web-panel-qa/public
export QA_SERVER=192.168.16.202
export QA_KEY=

export DEVELOPMENT_SOURCE_DIR=/var/www/web-panel/public/
export DEVELOPMENT_DEST_DIR=/var/web-panel-development/public
export DEVELOPMENT_SERVER=192.168.16.202
export DEVELOPMENT_KEY=

export ACCOUNT=norman
export RIGHTFUL_OWNER=root
