#!/bin/bash
DIR="$( cd "../$( dirname "$0" )" && pwd)"

while true; do
    read -p "==> Build for which OS? (Windows[W], OSX[O]) "
    case $REPLY in
        [Ww] )
            ./nwjs-shell-builder/nwjs-build.sh --src=$DIR/public --name=fluxAPP --version="1.0.0" --nw=0.12.3 --target="2 3" --build

            break;;

        [Oo] )
            ./nwjs-shell-builder/nwjs-build.sh --src=$DIR/public --name=fluxAPP --version="1.0.0" --nw=0.12.3 --target="4 5" --build

            break;;

        * )
            echo -e "Please chooce an specific OS"
    esac
done