#!/bin/bash
# ref: https://github.com/Gisto/nwjs-shell-builder
DIR="$( cd "../$( dirname "$0" )" && pwd)"
PACKAGE_NAME="FLUX_Studio"

DOWNLOAD_SOURCE="http://192.168.16.202"
# colors
TXT_NORMAL="\e[1m"
TXT_INFO="\e[32m"
TXT_WARNING="\e[93m"
TXT_ERROR="\e[31m"
TXT_RESET="\e[0m"

$DIR/_tools/nwjs-shell-builder/nwjs-build.sh --clean
rm -r $DIR/public/lib
mkdir -p $DIR/public/lib
cd $DIR

while true; do
    read -p "==> Build for which OS? (Windows[W], OSX[O], Linux[L]) "
    case $REPLY in
        [Ww] )
            printf "\n";
            printf "${TXT_INFO} Download Resources for Windows x86 ${TXT_RESET}";
            printf "\n";
            # dl latest ghost
            wget $DOWNLOAD_SOURCE/ghost/windows/fluxghost-win-latest-x86.zip
            # dl latest sli3er
            wget $DOWNLOAD_SOURCE/slic3r/windows/slic3r-mswin-x86-1-2-9a-stable.zip

            mv $DIR/_tools/fluxghost-win-latest-x86.zip $DIR/public/lib/fluxghost-windows-latest-x86.zip
            mv $DIR/_tools/slic3r-mswin-x86-1-2-9a-stable.zip $DIR/public/lib/slic3r-x86.zip

            unzip $DIR/public/lib/fluxghost-win-latest-x86.zip -d $DIR/public/lib/
            mv $DIR/public/lib/fluxghost-win-latest/assets $DIR/public/lib/assets
            mv $DIR/public/lib/fluxghost-win-latest/ghost $DIR/public/lib/ghost
            rm -r $DIR/public/lib/fluxghost-win-latest $DIR/public/lib/fluxghost-win-latest-x86.zip

            find /var/www/web-panel/public/lib/ -name "__MACOSX" | xargs rm -r

            printf "\n";
            printf "${TXT_INFO} Packing for Windows x86 ${TXT_RESET}";
            printf "\n";
            # dl latest ghost and sli3er (for x86)
            $DIR/_tools/nwjs-shell-builder/nwjs-build.sh --src=$DIR/public --name="$PACKAGE_NAME" --win-icon=$DIR/public/icon.png --version="1.0.0" --nw=0.12.3 --target="2" --build
            mv $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX_Studio-$(date +%Y%m%d)-win-ia32.zip $DIR/_tools/nwjs-shell-builder/TMP/output/fstudio-$(date +%Y%m%d)-win-x86.zip

            # clear
            rm -r $DIR/public/lib
            mkdir -p $DIR/public/lib

            printf "\n";
            printf "${TXT_INFO} Download Resources for Windows x64 ${TXT_RESET}";
            printf "\n";
            # dl latest ghost
            wget $DOWNLOAD_SOURCE/ghost/windows/fluxghost-win-latest-x64.zip
            # dl latest sli3er
            wget $DOWNLOAD_SOURCE/slic3r/windows/slic3r-mswin-x64-1-2-9a-stable.zip

            mv $DIR/_tools/fluxghost-win-latest-x64.zip $DIR/public/lib/fluxghost-windows-latest-x64.zip
            mv $DIR/_tools/slic3r-mswin-x64-1-2-9a-stable.zip $DIR/public/lib/slic3r-x64.zip

            unzip $DIR/public/lib/fluxghost-win-latest-x64.zip -d $DIR/public/lib/
            mv $DIR/public/lib/fluxghost-win-latest/assets $DIR/public/lib/assets
            mv $DIR/public/lib/fluxghost-win-latest/ghost $DIR/public/lib/ghost
            rm -r $DIR/public/lib/fluxghost-win-latest $DIR/public/lib/fluxghost-win-latest-x64.zip

            find /var/www/web-panel/public/lib/ -name "__MACOSX" | xargs rm -r

            printf "\n";
            printf "${TXT_INFO} Packing for Windows x64 ${TXT_RESET}";
            printf "\n";
            # # dl latest ghost and sli3er (for x64)
            $DIR/_tools/nwjs-shell-builder/nwjs-build.sh --src=$DIR/public --name="$PACKAGE_NAME" --win-icon=$DIR/public/icon.png --version="1.0.0" --nw=0.12.3 --target="3" --build
            mv $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX_Studio-$(date +%Y%m%d)-win-x64.zip $DIR/_tools/nwjs-shell-builder/TMP/output/fstudio-$(date +%Y%m%d)-win-x64.zip

            break;;

        [Oo] )
            printf "\n";
            printf "${TXT_INFO} Download Resources ${TXT_RESET}";
            printf "\n";
            # dl latest ghost
            wget $DOWNLOAD_SOURCE/ghost/osx/fluxghost-osx-latest.zip
            # dl latest sli3er
            wget $DOWNLOAD_SOURCE/slic3r/osx/slic3r.zip

            mv $DIR/_tools/fluxghost-osx-latest.zip $DIR/public/lib/fluxghost-osx-latest.zip
            mv $DIR/_tools/slic3r.zip $DIR/public/lib/slic3r.zip

            unzip $DIR/public/lib/fluxghost-osx-latest.zip -d $DIR/public/lib/
            mv $DIR/public/lib/fluxghost-osx-latest/assets $DIR/public/lib/assets
            mv $DIR/public/lib/fluxghost-osx-latest/ghost $DIR/public/lib/ghost
            rm -r $DIR/public/lib/fluxghost-osx-latest $DIR/public/lib/fluxghost-osx-latest.zip

            unzip $DIR/public/lib/slic3r.zip -d $DIR/public/lib/
            rm $DIR/public/lib/slic3r.zip

            find /var/www/web-panel/public/lib/ -name "__MACOSX" | xargs rm -r

            printf "\n";
            printf "${TXT_INFO} Building as APP ${TXT_RESET}"
            printf "\n";
            $DIR/_tools/nwjs-shell-builder/nwjs-build.sh --src=$DIR/public --name="$PACKAGE_NAME" --osx-icon=$DIR/public/logo.icns --version="1.0.0" --nw=0.12.3 --target="5" --build

            # build as a dmg
            mkdir -p $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX\ Studio
            printf "\n";
            printf "${TXT_INFO} Packing a dmg ${TXT_RESET}"
            printf "\n";
            unzip $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX_Studio-$(date +%Y%m%d)-osx-x64.zip -d $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX\ Studio
            mv $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX\ Studio/FLUX_Studio.app $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX\ Studio/FLUX\ Studio.app
            ln -s /Applications $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX\ Studio/Applications

            hdiutil create -size 400m -srcfolder $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX\ Studio/ $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX\ Studio/fstudio-$(date +%Y%m%d)-osx.dmg
            open $DIR/_tools/nwjs-shell-builder/TMP/output/FLUX\ Studio/

            break;;

        [Ll] )
            printf "\n";
            printf "${TXT_INFO} Download Resources for Linux ${TXT_RESET}";
            printf "\n";
            # dl latest ghost
            wget $DOWNLOAD_SOURCE/ghost/linux/fluxghost-linux-latest.zip
            # dl latest sli3er
            wget $DOWNLOAD_SOURCE/slic3r/linux/slic3r-linux-x86_64-1-2-9-stable.tar.gz

            mv $DIR/_tools/fluxghost-linux-latest.zip $DIR/public/lib/fluxghost-linux-latest.zip
            mv $DIR/_tools/slic3r-linux-x86_64-1-2-9-stable.tar.gz $DIR/public/lib/slic3r-linux-latest.tar.gz

            unzip $DIR/public/lib/slic3r-linux-latest.tar.gz -d $DIR/public/lib/
            mv $DIR/public/lib/fluxghost-linux-latest/assets $DIR/public/lib/assets
            mv $DIR/public/lib/fluxghost-linux-latest/ghost $DIR/public/lib/ghost
            rm -r $DIR/public/lib/fluxghost-linux-latest $DIR/public/lib/fluxghost-linux-latest.zip

            find /var/www/web-panel/public/lib/ -name "__MACOSX" | xargs rm -r

            printf "\n";
            printf "${TXT_INFO} Packing for Linux ${TXT_RESET}";
            printf "\n";
            ./nwjs-shell-builder/nwjs-build.sh --src=$DIR/public --name="$PACKAGE_NAME" --osx-icon=$DIR/public/logo.icns --version="1.0.0" --nw=0.12.3 --target="0 1" --build

            break;;

        * )
            echo -e "Please chooce the specific OS";
    esac
done

printf "${TXT_INFO} Done ${TXT_RESET}"
exit 0;