module.exports = {
    NOTIFY_LANGUAGE         : 'NOTIFY_LANGUAGE',
    NOTIFY_MACHINE_STATUS   : 'NOTIFY_MACHINE_STATUS',

    BACKEND_UP              : 'BACKEND_UP',
    BACKEND_DOWN            : 'BACKEND_DOWN',
    CHECK_BACKEND_STATUS    : 'CHECK_BACKEND_STATUS',
    NOTIFY_BACKEND_STATUS   : 'NOTIFY_BACKEND_STATUS',

    MENU_CLICK              : 'MENU_CLICK',
    DISABLE_MENU_ITEM       : 'DISABLE_MENU_ITEM',
    ENABLE_MENU_ITEM        : 'ENABLE_MENU_ITEM',

    POPUP_MENU              : 'POPUP_MENU_ITEM',

    UPDATE_ACCOUNT          : 'UPDATE_ACCOUNT',

    GET_AVAILABLE_FONTS     : 'GET_AVAILABLE_FONTS',
    FIND_FONTS              : 'FIND_FONTS',
    FIND_FONT               : 'FIND_FONT',

    SET_AS_DEFAULT          : 'SET_AS_DEFAULT'
};
